library(readxl)
Delhi <- read_excel("Delhi (1).xlsx", range = "A3:B2374")
View(Delhi)
str(Delhi)
Delhi$hms <- data.frame(do.call("rbind",strsplit(as.character(Delhi$date)," ",fixed = TRUE)))
Delhi$date <- as.Date(Delhi$hms$X1)
Delhi$hour<- Delhi$hms$X2
Delhi$pm25<- as.double(Delhi$pm25)
Delhi <- Delhi[,c(1,4,2)]
Delhi<- Delhi[order(Delhi$date),]
sum(is.na(Delhi$pm25))
#install.packages("imputeTS")
library("imputeTS")
Delhi$pm25 <- na_interpolation(Delhi$pm25)
class(Delhi)
nrow(Delhi)
ncol(Delhi)
head(Delhi)
tail(Delhi)
frequency(Delhi)
summary(Delhi$pm25)
length(unique(Delhi$pm25))
plot(Delhi$pm25~Delhi$date,Delhi)
library(tseries)
Delhits<- ts(Delhi$pm25,start = min(Delhi$date),end = max(Delhi$date))  
library(xts)
Delhits<- as.xts(Delhi)
class(Delhits)
plot(Delhits)
class(Delhi)
